{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k-view.serviceAccountName" . }}
  labels:
    {{- include "k-view.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k-view.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services", "namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k-view.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "k-view.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k-view.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
