{{- if or .Values.enable_sso .Values.localUsers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k-view.fullname" . }}-secret
  labels:
    {{- include "k-view.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.enable_sso }}
  googleClientId: {{ .Values.secrets.googleClientId | b64enc | quote }}
  googleClientSecret: {{ .Values.secrets.googleClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.localUsers }}
  KVIEW_STATIC_USERS: {{ .Values.localUsers | toJson | b64enc | quote }}
  {{- end }}
{{- end }}
