apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k-view.fullname" . }}-secret
  labels:
    {{- include "k-view.labels" . | nindent 4 }}
type: Opaque
data:
  googleClientId: {{ .Values.secrets.googleClientId | b64enc | quote }}
  googleClientSecret: {{ .Values.secrets.googleClientSecret | b64enc | quote }}
